name: Update PR Message

on:
  pull_request:
    types:
      - opened

jobs:
  update-pr-message:
    runs-on: ubuntu-latest

    steps:
      - name: Update PR Message
        run: |
          PR_NUMBER=$GITHUB_EVENT_NUMBER
          PR_BRANCH=$(echo $GITHUB_REF | awk 'BEGIN{FS="/"} {print $3}')
          NEW_MESSAGE="./merge_setup.sh -A -d $PR_BRANCH"
          UPDATED_MESSAGE=$(echo -e "$NEW_MESSAGE\n\n$(gh pr view $PR_NUMBER --json body -q .body)")
          gh pr edit $PR_NUMBER --body "$UPDATED_MESSAGE"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
