name: Update PR Template

on:
  pull_request:
    types:
      - opened

jobs:
  update-template:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract-branch

      - name: Create and Switch to a Temporary Branch
        run: |
          branch_name=$(echo "${{ steps.extract-branch.outputs.branch }}")
          git checkout -b temp-branch
          git reset --hard origin/$branch_name
        continue-on-error: true

      - name: Update PR Template
        run: |
          branch_name=$(echo "${{ steps.extract-branch.outputs.branch }}")
          sed -i "s|{{branch-name}}|$branch_name|" .github/PULL_REQUEST_TEMPLATE.md

          git add .github/PULL_REQUEST_TEMPLATE.md
          git commit -m "Update PR template with branch name"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
